### ISSUE TITLE
Disable swipe up and down

### ISSUE THREAD

**Issue by Siqlain-Hanif** [combisloic/swipable#2]

**Comment by Siqlain-Hanif** [comment]
Created this PR do review that.
https://github.com/loic-combis/swipable/pull/3

**Comment by davizgarzia** [comment]
Hi ! @Siqlain-Hanif 

Is there any way to disable swipe up and down ? 

Thank you :)

**Comment by Siqlain-Hanif** [comment]
Hi @davizgarzia 
I have done that in my forked version. You can use that it has a property verticalSwipe which you can set to false to disable the swipe up and down.
https://github.com/Siqlain-Hanif/swipable
