### ISSUE TITLE
Disable only direction

### ISSUE THREAD

**Issue by hsteinel** [combisloic/swipable#8]
Is it possible to disable only one direction?

**Comment by loic-combis** [comment]
Yes! You can use `verticalSwipe` or `horizontalSwipe`  (see README)

**Comment by hsteinel** [comment]
For your information. I found a bug in your verticalSwipe Calculation. 
No matter if you swiped up or down, swiped up is always true.
I solved it with this:
```
bool swipedUp = angle <0 && angle.abs () <(3 * math.pi / 4) && angle.abs ()> (math.pi / 4);
bool swipedDown = angle> 0 && angle.abs () <(3 * math.pi / 4) && angle.abs ()> (math.pi / 4);
```
